# Generated by Django 5.2 on 2025-05-18 09:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyCosmetics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skin_type', models.CharField(choices=[('oily', 'Oily'), ('dry', 'Dry'), ('combination', 'Combination'), ('normal', 'Normal')], max_length=20)),
                ('age', models.PositiveIntegerField()),
                ('concerns', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='CosmeticSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suggested_products', models.TextField()),
                ('user_preference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cosmetics.mycosmetics')),
            ],
        ),
    ]
